#!/bin/sh

##################################################
#
# GiantDisc mp3 Jukebox
# 
# © 2000-2002, Rolf Brugger
#
##################################################

#cd /home/music/database

echo "creating tables"
mysql < createtables.mysql

#echo "reading tracks"
#mysql < readtracks.mysql

#echo "reading albums"
#mysql < readalbums.mysql


echo "reading genres"
mysql --local-infile=1 < readgenres.mysql

echo "reading languages"
mysql --local-infile=1 < readlanguages.mysql

echo "reading musictypes"
mysql --local-infile=1 < readmusictypes.mysql

echo "reading sources"
mysql --local-infile=1 < readsources.mysql

#
